#!/usr/bin/env php
<?php
declare(strict_types = 1);

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\{
    Console\Application,
    DependencyInjection\ContainerBuilder,
    DependencyInjection\Loader\YamlFileLoader,
    DependencyInjection\Loader\PhpFileLoader,
    Config\FileLocator,
    Config\Loader\DelegatingLoader,
    Config\Loader\LoaderResolver
};

$container = new ContainerBuilder;
$loader = new DelegatingLoader(
    new LoaderResolver([
        new YamlFileLoader(
            $container,
            new FileLocator(__DIR__.'/src/Resources/config')
        ),
        new PhpFileLoader(
            $container,
            new FileLocator(__DIR__.'/src/Resources/config')
        ),
    ])
);
$loader->load('services.yml');
$container->compile();

$app = new Application('ExpenseManager');
$app->add($container->get('command.init'));
$app->add($container->get('command.category.create'));
$app->add($container->get('command.budget.create'));
$app->run();
