#!/usr/bin/env php
<?php
declare(strict_types = 1);

require __DIR__.'/vendor/autoload.php';

use Innmind\EventBusBundle\DependencyInjection\Compiler\{
    BuildEventBusStackPass,
    RegisterListenersPass
};
use Symfony\Component\{
    Console\Application,
    DependencyInjection\ContainerBuilder,
    DependencyInjection\Loader\YamlFileLoader,
    DependencyInjection\Loader\PhpFileLoader,
    Config\FileLocator,
    Config\Loader\DelegatingLoader,
    Config\Loader\LoaderResolver
};

$container = new ContainerBuilder;
$loader = new DelegatingLoader(
    new LoaderResolver([
        new YamlFileLoader(
            $container,
            new FileLocator(__DIR__.'/src/Resources/config')
        ),
        new PhpFileLoader(
            $container,
            new FileLocator(__DIR__.'/src/Resources/config')
        ),
    ])
);
$loader->load('services.yml');
$container
    ->addCompilerPass(new BuildEventBusStackPass)
    ->addCompilerPass(new RegisterListenersPass);
$container->compile();

$app = new Application('ExpenseManager');
$app->add($container->get('command.init'));
$app->add($container->get('command.category.create'));
$app->add($container->get('command.category.list'));
$app->add($container->get('command.budget.create'));
$app->add($container->get('command.budget.list'));
$app->add($container->get('command.expense.create'));
$app->add($container->get('command.expense.list'));
$app->add($container->get('command.one_off_income.create'));
$app->add($container->get('command.one_off_income.list'));
$app->add($container->get('command.fixed_cost.create'));
$app->add($container->get('command.fixed_cost.list'));
$app->add($container->get('command.income.create'));
$app->add($container->get('command.income.list'));
$app->run();
