parameters:
    innmind_command_bus.stack:
        - queue
        - clear_entities_recorded_events
        - dispatch_domain_events
        - flush
        - default

services:
    command_bus: '@innmind_command_bus'

    innmind_command_bus.default:
        class: Innmind\CommandBusBundle\ContainerAwareCommandBus
        arguments:
            - '@service_container'
            - []
        factory:
            - Innmind\CommandBusBundle\Factory\ContainerAwareCommandBusFactory
            - make
        tags:
            - { name: innmind_command_bus, alias: default }

    command_bus.flush:
        class: ExpenseManager\Cli\CommandBus\FlushCommandBus
        arguments:
            - ~
            - '@storage.unit_of_work'
            - '@storage.persistence'
        tags:
            - { name: innmind_command_bus, alias: flush }

    command_bus.dispatch_domain_events:
        class: ExpenseManager\Cli\CommandBus\DispatchDomainEventsCommandBus
        arguments:
            - ~
            - '@storage.unit_of_work'
            - '@event_bus'
        tags:
            - { name: innmind_command_bus, alias: dispatch_domain_events }

    command_bus.clear_entities_recorded_events:
        class: ExpenseManager\Cli\CommandBus\ClearEntitiesRecordedEventsCommandBus
        arguments:
            - ~
            - '@storage.unit_of_work'
        tags:
            - { name: innmind_command_bus, alias: clear_entities_recorded_events }

    command_bus.queue:
        class: Innmind\CommandBus\QueueableCommandBus
        arguments:
            - ~
        tags:
            - { name: innmind_command_bus, alias: queue }
