services:
    event_dispatcher:
        class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
        arguments:
            - '@service_container'

    listener.disable_command_while_not_initialized:
        class: ExpenseManager\Cli\EventListener\DisableCommandWhileNotInitializedListener
        arguments:
            - '@storage.config'
        tags:
            - { name: kernel.event_subscriber }

    listener.create_month_report:
        class: ExpenseManager\Cli\EventListener\CreateMonthReportListener
        arguments:
            - '@repository.month_report'
            - '@innmind_command_bus'
        tags:
            - { name: kernel.event_subscriber }
