parameters:
    innmind_event_bus.stack:
        - queue
        - default

services:
    event_bus: '@innmind_event_bus'

    innmind_event_bus.default:
        class: Innmind\EventBusBundle\ContainerAwareEventBus
        arguments:
            - '@service_container'
            - []
        factory:
            - Innmind\EventBusBundle\Factory\ContainerAwareEventBusFactory
            - make
        tags:
            - { name: innmind_event_bus, alias: default }

    event_bus.queue:
        class: Innmind\EventBus\QueueableEventBus
        arguments:
            - ~
        tags:
            - { name: innmind_event_bus, alias: queue }

    listener.month_report.apply_expense:
        class: ExpenseManager\Cli\EventListener\MonthReport\ApplyExpenseListener
        arguments:
            - '@innmind_command_bus'
        tags:
            - { name: innmind_event_bus.listener, listen_to: ExpenseManager\Event\ExpenseWasCreated }

    listener.month_report.apply_one_off_income:
        class: ExpenseManager\Cli\EventListener\MonthReport\ApplyOneOffIncomeListener
        arguments:
            - '@innmind_command_bus'
        tags:
            - { name: innmind_event_bus.listener, listen_to: ExpenseManager\Event\OneOffIncomeWasCreated }
