services:
    handler.create_budget:
        class: ExpenseManager\Handler\CreateBudgetHandler
        arguments:
            - '@repository.budget'
            - '@repository.category'

    handler.create_category:
        class: ExpenseManager\Handler\CreateCategoryHandler
        arguments:
            - '@repository.category'

    handler.create_expense:
        class: ExpenseManager\Handler\CreateExpenseHandler
        arguments:
            - '@repository.expense'
            - '@repository.category'

    handler.specify_expense_note:
        class: ExpenseManager\Handler\SpecifyExpenseNoteHandler
        arguments:
            - '@repository.expense'
