services:
    handler.create_budget:
        class: ExpenseManager\Handler\CreateBudgetHandler
        arguments:
            - '@repository.budget'
            - '@repository.category'
        tags:
            - { name: innmind_command_bus.handler, handles: ExpenseManager\Command\CreateBudget }

    handler.create_category:
        class: ExpenseManager\Handler\CreateCategoryHandler
        arguments:
            - '@repository.category'
        tags:
            - { name: innmind_command_bus.handler, handles: ExpenseManager\Command\CreateCategory }

    handler.create_expense:
        class: ExpenseManager\Handler\CreateExpenseHandler
        arguments:
            - '@repository.expense'
            - '@repository.category'
        tags:
            - { name: innmind_command_bus.handler, handles: ExpenseManager\Command\CreateExpense }

    handler.specify_expense_note:
        class: ExpenseManager\Handler\SpecifyExpenseNoteHandler
        arguments:
            - '@repository.expense'
        tags:
            - { name: innmind_command_bus.handler, handles: ExpenseManager\Command\SpecifyExpenseNote }

    handler.create_one_off_income:
        class: ExpenseManager\Handler\CreateOneOffIncomeHandler
        arguments:
            - '@repository.one_off_income'
        tags:
            - { name: innmind_command_bus.handler, handles: ExpenseManager\Command\CreateOneOffIncome }

    handler.specify_one_off_income_note:
        class: ExpenseManager\Handler\SpecifyOneOffIncomeNoteHandler
        arguments:
            - '@repository.one_off_income'
        tags:
            - { name: innmind_command_bus.handler, handles: ExpenseManager\Command\SpecifyOneOffIncomeNote }

    handler.create_fixed_cost:
        class: ExpenseManager\Handler\CreateFixedCostHandler
        arguments:
            - '@repository.fixed_cost'
            - '@repository.category'
        tags:
            - { name: innmind_command_bus.handler, handles: ExpenseManager\Command\CreateFixedCost }

    handler.create_income:
        class: ExpenseManager\Handler\CreateIncomeHandler
        arguments:
            - '@repository.income'
        tags:
            - { name: innmind_command_bus.handler, handles: ExpenseManager\Command\CreateIncome }

    handler.create_month_report:
        class: ExpenseManager\Handler\CreateCurrentMonthReportHandler
        arguments:
            - '@repository.month_report'
        tags:
            - { name: innmind_command_bus.handler, handles: ExpenseManager\Command\CreateCurrentMonthReport }

    handler.generate_old_month_report:
        class: ExpenseManager\Handler\GenerateOldMonthReportHandler
        arguments:
            - '@repository.month_report'
            - '@repository.income'
            - '@repository.fixed_cost'
        tags:
            - { name: innmind_command_bus.handler, handles: ExpenseManager\Command\GenerateOldMonthReport }

    handler.month_report.apply_expense:
        class: ExpenseManager\Handler\MonthReport\ApplyExpenseHandler
        arguments:
            - '@repository.month_report'
            - '@repository.expense'
        tags:
            - { name: innmind_command_bus.handler, handles: ExpenseManager\Command\MonthReport\ApplyExpense }

    handler.month_report.apply_income:
        class: ExpenseManager\Handler\MonthReport\ApplyIncomeHandler
        arguments:
            - '@repository.month_report'
            - '@repository.income'
        tags:
            - { name: innmind_command_bus.handler, handles: ExpenseManager\Command\MonthReport\ApplyIncome }

    handler.month_report.apply_fixed_cost:
        class: ExpenseManager\Handler\MonthReport\ApplyFixedCostHandler
        arguments:
            - '@repository.month_report'
            - '@repository.fixed_cost'
        tags:
            - { name: innmind_command_bus.handler, handles: ExpenseManager\Command\MonthReport\ApplyFixedCost }

    handler.month_report.apply_one_off_income:
        class: ExpenseManager\Handler\MonthReport\ApplyOneOffIncomeHandler
        arguments:
            - '@repository.month_report'
            - '@repository.one_off_income'
        tags:
            - { name: innmind_command_bus.handler, handles: ExpenseManager\Command\MonthReport\ApplyOneOffIncome }
