imports:
    - { resource: env.php }
    - { resource: storage.yml }
    - { resource: repositories.yml }
    - { resource: handlers.yml }

services:
    storage.config:
        class: Innmind\Filesystem\Adapter\FilesystemAdapter
        arguments:
            - %user_home%

    command.init:
        class: ExpenseManager\Cli\Command\InitCommand
        arguments:
            - '@storage.config'

    command.category.create:
        class: ExpenseManager\Cli\Command\Category\CreateCommand
        arguments:
            - '@command_bus'

    command.budget.create:
        class: ExpenseManager\Cli\Command\Budget\CreateCommand
        arguments:
            - '@command_bus'
            - '@repository.category'

    command.budget.list:
        class: ExpenseManager\Cli\Command\Budget\ListCommand
        arguments:
            - '@repository.budget'
            - '@repository.category'

    command.expense.create:
        class: ExpenseManager\Cli\Command\Expense\CreateCommand
        arguments:
            - '@command_bus'
            - '@repository.category'

    command.one_off_income.create:
        class: ExpenseManager\Cli\Command\OneOffIncome\CreateCommand
        arguments:
            - '@command_bus'

    command.fixed_cost.create:
        class: ExpenseManager\Cli\Command\FixedCost\CreateCommand
        arguments:
            - '@command_bus'
            - '@repository.category'

    command.income.create:
        class: ExpenseManager\Cli\Command\Income\CreateCommand
        arguments:
            - '@command_bus'

    command_bus: '@command_bus.flush'

    command_bus.default:
        class: Innmind\CommandBus\CommandBus
        arguments:
            -
                ExpenseManager\Command\CreateBudget: '@handler.create_budget'
                ExpenseManager\Command\CreateCategory: '@handler.create_category'
                ExpenseManager\Command\CreateExpense: '@handler.create_expense'
                ExpenseManager\Command\SpecifyExpenseNote: '@handler.specify_expense_note'
                ExpenseManager\Command\CreateOneOffIncome: '@handler.create_one_off_income'
                ExpenseManager\Command\SpecifyOneOffIncomeNote: '@handler.specify_one_off_income_note'
                ExpenseManager\Command\CreateFixedCost: '@handler.create_fixed_cost'
                ExpenseManager\Command\CreateIncome: '@handler.create_income'
        factory:
            - ExpenseManager\Cli\Factory\CommandBusFactory
            - make

    command_bus.flush:
        class: ExpenseManager\Cli\CommandBus\FlushCommandBus
        arguments:
            - '@command_bus.default'
            - '@storage.unit_of_work'
            - '@storage.persistence'
