services:
    storage.config:
        class: Innmind\Filesystem\Adapter\FilesystemAdapter
        arguments:
            - %user_home%

    storage.denormalizer.budget:
        class: ExpenseManager\Cli\Storage\Denormalizer\BudgetDenormalizer
        public: false

    storage.denormalizer.category:
        class: ExpenseManager\Cli\Storage\Denormalizer\CategoryDenormalizer
        public: false

    storage.denormalizer.expense:
        class: ExpenseManager\Cli\Storage\Denormalizer\ExpenseDenormalizer
        public: false

    storage.denormalizer.fixed_cost:
        class: ExpenseManager\Cli\Storage\Denormalizer\FixedCostDenormalizer
        public: false

    storage.denormalizer.income:
        class: ExpenseManager\Cli\Storage\Denormalizer\IncomeDenormalizer
        public: false

    storage.denormalizer.one_off_income:
        class: ExpenseManager\Cli\Storage\Denormalizer\OneOffIncomeDenormalizer
        public: false

    storage.normalizer.budget:
        class: ExpenseManager\Cli\Storage\Normalizer\BudgetNormalizer
        public: false

    storage.normalizer.category:
        class: ExpenseManager\Cli\Storage\Normalizer\CategoryNormalizer
        public: false

    storage.normalizer.expense:
        class: ExpenseManager\Cli\Storage\Normalizer\ExpenseNormalizer
        public: false

    storage.normalizer.fixed_cost:
        class: ExpenseManager\Cli\Storage\Normalizer\FixedCostNormalizer
        public: false

    storage.normalizer.income:
        class: ExpenseManager\Cli\Storage\Normalizer\IncomeNormalizer
        public: false

    storage.normalizer.one_off_income:
        class: ExpenseManager\Cli\Storage\Normalizer\OneOffIncomeNormalizer
        public: false

    storage.unit_of_work:
        class: ExpenseManager\Cli\Storage\UnitOfWork
        public: false
        arguments:
            -
                - ExpenseManager\Entity\Budget
                - ExpenseManager\Entity\Category
                - ExpenseManager\Entity\Expense
                - ExpenseManager\Entity\FixedCost
                - ExpenseManager\Entity\Income
                - ExpenseManager\Entity\OneOffIncome
        factory:
            - ExpenseManager\Cli\Factory\UnitOfWorkFactory
            - make

    storage.persistence:
        class: ExpenseManager\Cli\Storage\Persistence
        public: false
        arguments:
            -
                ExpenseManager\Entity\Budget: '@storage.adapter.budget'
                ExpenseManager\Entity\Category: '@storage.adapter.category'
                ExpenseManager\Entity\Expense: '@storage.adapter.expense'
                ExpenseManager\Entity\FixedCost: '@storage.adapter.fixed_cost'
                ExpenseManager\Entity\Income: '@storage.adapter.income'
                ExpenseManager\Entity\OneOffIncome: '@storage.adapter.one_off_income'
            -
                ExpenseManager\Entity\Budget: '@storage.normalizer.budget'
                ExpenseManager\Entity\Category: '@storage.normalizer.category'
                ExpenseManager\Entity\Expense: '@storage.normalizer.expense'
                ExpenseManager\Entity\FixedCost: '@storage.normalizer.fixed_cost'
                ExpenseManager\Entity\Income: '@storage.normalizer.income'
                ExpenseManager\Entity\OneOffIncome: '@storage.normalizer.one_off_income'
            -
                ExpenseManager\Entity\Budget: '@storage.denormalizer.budget'
                ExpenseManager\Entity\Category: '@storage.denormalizer.category'
                ExpenseManager\Entity\Expense: '@storage.denormalizer.expense'
                ExpenseManager\Entity\FixedCost: '@storage.denormalizer.fixed_cost'
                ExpenseManager\Entity\Income: '@storage.denormalizer.income'
                ExpenseManager\Entity\OneOffIncome: '@storage.denormalizer.one_off_income'
            - '@storage.unit_of_work'
        factory:
            - ExpenseManager\Cli\Factory\PersistenceFactory
            - make

    storage.adapter.budget:
        class: Innmind\Filesystem\Adapter\FilesystemAdapter
        public: false
        arguments:
            - '%wallet_path%/budget'

    storage.adapter.category:
        class: Innmind\Filesystem\Adapter\FilesystemAdapter
        public: false
        arguments:
            - '%wallet_path%/category'

    storage.adapter.expense:
        class: Innmind\Filesystem\Adapter\FilesystemAdapter
        public: false
        arguments:
            - '%wallet_path%/expense'

    storage.adapter.fixed_cost:
        class: Innmind\Filesystem\Adapter\FilesystemAdapter
        public: false
        arguments:
            - '%wallet_path%/fixed_cost'

    storage.adapter.income:
        class: Innmind\Filesystem\Adapter\FilesystemAdapter
        public: false
        arguments:
            - '%wallet_path%/income'

    storage.adapter.one_off_income:
        class: Innmind\Filesystem\Adapter\FilesystemAdapter
        public: false
        arguments:
            - '%wallet_path%/one_off_income'
