services:
    storage.denormalizer.budget:
        class: ExpenseManagerCli\Storage\Denormalizer\BudgetDenormalizer
        public: false

    storage.denormalizer.category:
        class: ExpenseManagerCli\Storage\Denormalizer\CategoryDenormalizer
        public: false

    storage.denormalizer.expense:
        class: ExpenseManagerCli\Storage\Denormalizer\ExpenseDenormalizer
        public: false

    storage.denormalizer.fixed_cost:
        class: ExpenseManagerCli\Storage\Denormalizer\FixedCostDenormalizer
        public: false

    storage.denormalizer.income:
        class: ExpenseManagerCli\Storage\Denormalizer\IncomeDenormalizer
        public: false

    storage.denormalizer.one_off_income:
        class: ExpenseManagerCli\Storage\Denormalizer\OneOffIncomeDenormalizer
        public: false

    storage.normalizer.budget:
        class: ExpenseManagerCli\Storage\Normalizer\BudgetNormalizer
        public: false

    storage.normalizer.category:
        class: ExpenseManagerCli\Storage\Normalizer\CategoryNormalizer
        public: false

    storage.normalizer.expense:
        class: ExpenseManagerCli\Storage\Normalizer\ExpenseNormalizer
        public: false

    storage.normalizer.fixed_cost:
        class: ExpenseManagerCli\Storage\Normalizer\FixedCostNormalizer
        public: false

    storage.normalizer.income:
        class: ExpenseManagerCli\Storage\Normalizer\IncomeNormalizer
        public: false

    storage.normalizer.one_off_income:
        class: ExpenseManagerCli\Storage\Normalizer\OneOffIncomeNormalizer
        public: false

    storage.unit_of_work:
        class: ExpenseManagerCli\Storage\UnitOfWork
        public: false
        arguments:
            -
                - ExpenseManager\Entity\Budget
                - ExpenseManager\Entity\Category
                - ExpenseManager\Entity\Expense
                - ExpenseManager\Entity\FixedCost
                - ExpenseManager\Entity\Income
                - ExpenseManager\Entity\OneOffIncome
        factory:
            - ExpenseManagerCli\Factory\UnitOfWorkFactory
            - make

    storage.persistence:
        class: ExpenseManagerCli\Storage\Persistence
        public: false
        arguments:
            - '@storage.filesystem'
            -
                ExpenseManager\Entity\Budget: budget
                ExpenseManager\Entity\Category: category
                ExpenseManager\Entity\Expense: expense
                ExpenseManager\Entity\FixedCost: fixed_cost
                ExpenseManager\Entity\Income: income
                ExpenseManager\Entity\OneOffIncome: one_off_income
            -
                ExpenseManager\Entity\Budget: '@storage.normalizer.budget'
                ExpenseManager\Entity\Category: '@storage.normalizer.category'
                ExpenseManager\Entity\Expense: '@storage.normalizer.expense'
                ExpenseManager\Entity\FixedCost: '@storage.normalizer.fixed_cost'
                ExpenseManager\Entity\Income: '@storage.normalizer.income'
                ExpenseManager\Entity\OneOffIncome: '@storage.normalizer.one_off_income'
            -
                ExpenseManager\Entity\Budget: '@storage.denormalizer.budget'
                ExpenseManager\Entity\Category: '@storage.denormalizer.category'
                ExpenseManager\Entity\Expense: '@storage.denormalizer.expense'
                ExpenseManager\Entity\FixedCost: '@storage.denormalizer.fixed_cost'
                ExpenseManager\Entity\Income: '@storage.denormalizer.income'
                ExpenseManager\Entity\OneOffIncome: '@storage.denormalizer.one_off_income'
            - '@storage.unit_of_work'
        factory:
            - ExpenseManagerCli\Factory\PersistenceFactory
            - make

    storage.filesystem:
        class: ExpenseManagerCli\Storage\FilesystemAdapter
        public: false
        arguments:
            - '%wallet_path%'
